---
language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.5.0"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
notifications:
  email: false
